### ISSUE TITLE
Error with missing validate-npm-package-name package when running npx create-contentful-app

### ISSUE THREAD

**Issue by brett-east** [contentful/create-contentful-app#1123]
I'm running into this error when trying to run `npx create-contentful-app test-app`

```
Error: Cannot find module 'validate-npm-package-name'
Require stack:
- /Users/bretteast/.npm/_npx/a25b92dfae1d563c/node_modules/contentful--create-contentful-app/lib/index.js
```

Is there an additional step that needs to occur?

**Comment by brett-east** [comment]
I want to note that running `npx @contentful/create-contentful-app` does in fact work, but that all the documentation I've seen including the messages I get after running `npx @contentful/create-contentful-app`, say to use `npx create-contentful-app` and that is not working for me.

**Comment by andipaetzold** [comment]
👋 Hey @brett-east 

I was able to reproduce the issue and will look into it now 👀

**Comment by andipaetzold** [comment]
Seems like the shrinkwraps don't play well with lerna.

`npx create-contentful-app` should now work again. Sorry for the troubles!
