### ISSUE TITLE
Building mutlple fields in one App

### ISSUE THREAD

**Issue by tomprats** [contentful/create-contentful-app#1232]
I recently finished building a config-screen and field in a create-contentful-app. It works great, everything looks good on contentful.com after I bundled it and pushed it up.

My next task is to build another field to use on Contentful. Is it possible to have 2 separate field widgets in one create-contentful-app?

My reason for including them in the same app is that there are a variety of helpers/hooks that I would use in both. So optimally I could be both in the same repo/app.

**Comment by martin3walker** [comment]
Hey Tom,

It would be possible to have two apps in the same repo, as long as their build processes were kept separate. So you could have a parent folder which contained all of the shared functionality you'd like to use in both apps. Then two "packages" which would be your separate apps. Each would have their own package.json and dependencies, but could import functions from the parent folder. In essence, [a monorepo](https://monorepo.tools/), though I don't know if its worth setting up a monorepo tool unless the project will grow.

You could take a look at our [marketplace apps repo](https://github.com/contentful/apps) for an example. Just check out the 'apps' folder in the project

**Comment by martin3walker** [comment]
Sounds good :)
