### ISSUE TITLE
Missing loading variable check in documentation

### ISSUE THREAD

**Issue by V-iktor** [contentful/create-contentful-app#1311]
Is there a way to check if useFieldValue is fetching data to show a progress animation while loading data from Contentful inside React?

https://www.npmjs.com/package/@contentful/react-apps-toolkit

**Comment by andipaetzold** [comment]
`useFieldValue` is never in a loading state. Therefore, we do not export one.

The values are fetched while the app is initialized (`init` or via `SDKProvider`) and always kept up-to-date after that. There is never a state where the app is waiting for a network request or similar to get access to a value.
