### ISSUE TITLE
Missing authentication in documentation

### ISSUE THREAD

**Issue by V-iktor** [contentful/create-contentful-app#1312]
I am migrating from the unmaintained react-contentful and trying to use @contentful/react-apps-toolkit instead.

So I am wondering how to use the authentication for useFieldValue is set up.

**Comment by andipaetzold** [comment]
`react-contentful` is not an official Contentful library, so I don't have much context about that.
With `useFieldValue` you can access the field values of the entry you are currently editing. Therefore you do not need to handle authentication.
To access other entries using the CMA, you can use `useCMA` and, again, authentication is already handled for you.

Did you run into any issues?
