### ISSUE TITLE
Forma 36 tokens missing in Index.tsx

### ISSUE THREAD

**Issue by struckm** [contentful/create-contentful-app#140]
When first creating an app with the cli, the import for Forma 36 tokens is missing. I ran into an issue with the Select control not styling properly. Once I realized that the Custom properties(CSS variables) were missing, I added
`
import '@contentful/forma-36-tokens/dist/css/index.css';
`
to the Index.tsx file and everything styled correctly. 

I believe that file should be included by default

**Comment by Jwhiles** [comment]
Hey, thanks for pointing this out. I think this was overlooked because the default app template doesn't involve many forma components
