### ISSUE TITLE
App Scripts Depends on Vulnerable Axios Package

### ISSUE THREAD

**Issue by sherl0cks** [contentful/create-contentful-app#1773]
```
devDependencies:
@contentful/app-scripts 1.13.0
├─┬ analytics-node 6.2.0
│ └── axios 0.27.2
```
![Screenshot 2023-11-13 at 4 05 16 PM](https://github.com/contentful/create-contentful-app/assets/1335137/25cfbe58-25a9-4ef2-98a4-58502b03dc0e)

**Comment by jjolton-contentful** [comment]
Resolved in v1.2.131 🎉
