### ISSUE TITLE
Package dependency error for non-existent version of @contentful/f36-core 

### ISSUE THREAD

**Issue by mpalazzo-dl** [contentful/create-contentful-app#1826]
When I run an npm install, I get the following error:

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @contentful/f36-core@^4.58.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

Looks like the latest version of this package is 4.57, but there is a dependency looking for 4.58 which is preventing package install

**Comment by ghepting** [comment]
Thanks for reporting this! We got the issue resolved :)
