### ISSUE TITLE
npm error on installation

### ISSUE THREAD

**Issue by jacobsilver2** [contentful/create-contentful-app#230]
after running npx @contentful/create-contentful-app init my-first-app , I get the following:

npm ERR! Found: type-fest@0.20.2
npm ERR! node_modules/type-fest
npm ERR!   type-fest@"0.20.2" from contentful-management@7.5.1
npm ERR!   node_modules/contentful-management
npm ERR!     contentful-management@"^7.5.1" from @contentful/cra-template-create-contentful-app@0.3.3
npm ERR!

     node_modules/@contentful/cra-template-create-contentful-app
npm ERR!       @contentful/cra-template-create-contentful-app@"*" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional type-fest@"^0.13.1" from @pmmmwh/react-refresh-webpack-plugin@0.4.2
npm ERR! node_modules/@pmmmwh/react-refresh-webpack-plugin
npm ERR!   @pmmmwh/react-refresh-webpack-plugin@"0.4.2" from react-scripts@4.0.1
npm

 ERR!   node_modules/react-scripts
npm ERR!     react-scripts@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

**Comment by andipaetzold** [comment]
Hey @jacobsilver2 

there seems to be an issue with npm 7 as it is still under active development and has several bugs.
Can you try downgrading to a node LTS version (10, 12 or 14) and see whether you still get this error?

**Comment by tasnuva1** [comment]
You can use node version manager like **nvm** for windows.
For easily switching between node versions.
For detailed instruction and info about NVM  -- you can see this video: https://youtu.be/px9N1JOzRVU

**Comment by jacobsilver2** [comment]
ah ok, figured it was something like that. Thank you!

**Comment by jacobsilver2** [comment]
downgrading to node v14 did the trick.
