### ISSUE TITLE
Reopen issue #213 --->I can't log in

### ISSUE THREAD

**Issue by tasnuva1** [contentful/create-contentful-app#232]
Please reopen issue #213.

**Details of the Issue itself:**

I can't log in. 

_**The session expired
Please authenticate again.**_

For reproducing it: Just watch those videos.

[First Video](https://www.dropbox.com/s/hpqo6qxvykcpd6g/20210113_174806.mp4?dl=0)

[Second One](https://www.dropbox.com/s/qnz6ae7ar03g8td/20210113_180129.mp4?dl=0)

[Third One](https://www.dropbox.com/s/jcxv6hrcrcj341k/20210113_181040.mp4?dl=0)

why this is happening? Just Let me know.
By the way, the authentication route is not secure (http://app.contentful.com/)
Just guessing, It maybe blocks my IP address or something that I can't log in and can't even signup for it.

**Comment by VaguelySerious** [comment]
@tasnuva1 Hi there, thanks for sharing the recordings.

Can you try using a different browser, preferably one that does not have any add-ons installed?
All Contentful services are offered over a secure connection (HTTPS), and should automatically redirect you to a secure version of the site if you are trying to access it over regular HTTP. If you are still seeing an insecure connection after trying with a different browser and disabling add-ons, try manually going to `https://be.contentful.com`, or replacing `http` with `https` in the browser URL bar.

**Comment by tasnuva1** [comment]
Thanks for the solution to solve the problem. Unfortunately, the authentication route is still not secure. 

I try to clear my browser( Chrome ) history, disable all the extensions, and change the site settings to Pop-ups and redirects, Ads to allow, and when It's doesn't work, I change in to block. I try manually going to https://be.contentful.com. -->still not secure.

I also try in Opera Browser. Still not secure.

But fortunately, It's fully working and secure on my mobile device. 
So, I'm gonna use it on there. I have no choice.

**Comment by VaguelySerious** [comment]
In this case, it might be an issue with how your device handles network connections, or there might be some other software on your device that changes the behavior.
I'm closing this issue now as it seems to be related to the setup your are using, and unrelated to any of the services offered by Contentful.
