### ISSUE TITLE
Broken dependency for type-fest 0.13.1

### ISSUE THREAD

**Issue by hgeistcb** [contentful/create-contentful-app#243]
Trying to create a new contentful app on the console via "npx @contentful/create-contentful-app init my-first-app" fails since around Christmas time 2020 with the following error:

`Creating a Contentful app in ~/my-first-app.

Creating a new React app in /home/w6/my-first-app.

Installing packages. This might take a couple of minutes.

Installing react, react-dom, and react-scripts with @contentful/cra-template-create-contentful-app...

npm 

ERR! code ERESOLVE

npm ERR!

 ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: type-fest@0.20.2
npm ERR! node_modules/type-fest
npm ERR!   type-fest@"0.20.2" from contentful-management@7.5.1
npm ERR!   node_modules/contentful-management
npm ERR!     contentful-management@"^7.5.1" from @contentful/cra-template-create-contentful-app@0.3.3
npm ERR!     node_modules/@contentful/cra-template-create-contentful-app
npm ERR!       @contentful/cra-template-create-contentful-app@"*" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm 

ERR! peerOptional type-fest@"^0.13.1" from @pmmmwh/react-refresh-webpack-plugin@0.4.2
npm ERR! node_modules/@pmmmwh/react-refresh-webpack-plugin
npm ERR!   @pmmmwh/react-refresh-webpack-plugin@"0.4.2" from react-scripts@4.0.1
npm ERR!   node_modules/react-scripts
npm ERR!     react-scripts@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm 
`

node version is 14 LTS.

Please fix this asap, we depend on the contentful app framework, since you declared extensions as deprecated.

**Comment by kdamball** [comment]
@hgeistcb what npm version are you on?

**Comment by hgeistcb** [comment]
@kdamball : Hello, its 7.0.15

OS: xubuntu 20.04

**Comment by kdamball** [comment]
We just updated the [recommended npm version](https://github.com/contentful/create-contentful-app/pull/236) as npm v7 breaks when using `npx`.
