### ISSUE TITLE
Initializing new apps is not working

### ISSUE THREAD

**Issue by alighali85** [contentful/create-contentful-app#303]
when trying to use the cli per the construction in the  Readme file, I am getting the following error:
```
You are running `create-react-app` 4.0.1, which is behind the latest release (4.0.3).
```

**Comment by VaguelySerious** [comment]
Hey @alighali85, this is likely due to your local setup containing a global install of `create-react-app`.

The full error message should look something like this:
```
You are running `create-react-app` 4.0.1, which is behind the latest release (4.0.3).
We no longer support global installation of Create React App.
Please remove any global installs with one of the following commands:
- npm uninstall -g create-react-app
- yarn global remove create-react-app
The latest instructions for creating a new app can be found here:
https://create-react-app.dev/docs/getting-started/
```

Please let us know if the steps outlined in the error message don't fix your problem.

**Comment by Jwhiles** [comment]
Hey @alighali85 - I'm going to close this issue now. But feel free to re-open it if the above comment did not solve this for you.
