### ISSUE TITLE
Dev dependencies are added as regular dependencies

### ISSUE THREAD

**Issue by kamsar** [contentful/create-contentful-app#51]
In the template file (https://github.com/contentful/create-contentful-app/blob/master/template.json) it's making all the created project dependencies full dependencies (including say typescript, react-scripts, and testing-library that would normally be devDependencies).

Is there a reason for that?

**Comment by Jwhiles** [comment]
Hey Kamsar, this looks like an oversight. Thanks for pointing it out. I'll update the template.

**Comment by Jwhiles** [comment]
I've looked into this, and create-react-app, which we are using under the hood excludes dev-dependencies that are included in custom templates. There is some discussion of the issue [here](https://github.com/facebook/create-react-app/issues/8082) and [here](https://github.com/facebook/create-react-app/issues/8371).

I'm going to close this issue for now, but will be look again if create-react-app changes.
