### ISSUE TITLE
New create-contentful-app is not compiling due to type errors

### ISSUE THREAD

**Issue by stefanjudis** [contentful/create-contentful-app#71]
Hey friends, I justcreated a fresh app using `npx create-contentful-app init contentful-markdown-display`. When I now run `npm start` I see the following. 👇

<img width="1071" alt="image" src="https://user-images.githubusercontent.com/962099/92578959-e1736200-f28c-11ea-8786-02b92c7f1eab.png">

<img width="1045" alt="image" src="https://user-images.githubusercontent.com/962099/92578998-ee905100-f28c-11ea-98b2-93481b8fab6e.png">

It looks like some typings are incompatible after the UI extension update that happened yday? 

Thanks a bunch for looking into this! 🙇‍♂️

## Update

I can confirm that backporting of the extensions sdk from  `3.23.1` to `3.23.0` in the `package.son` (`"contentful-ui-extensions-sdk": "3.23.0",`) fixes the typing error. :)

**Comment by Jwhiles** [comment]
fixed in #69
