### ISSUE TITLE
Unable to create project

### ISSUE THREAD

**Issue by rickykissoon** [contentful/create-contentful-app#758]
``You are running 'create-react-app' 4.0.3, which is behind the latest release (5.0.0).``
``We no longer support global installation of Create React App.``

I receive the above message and Im told to uninstall globals. Ive done this several times and no matter what create-contentful-app does not run. The react version (create-react-app) works flawlessly. This project worked yesterday, and began failing today, which is why I deleted the project and attempted to start from scratch.  Any help would be greatly appreciated.

**Comment by loweisz** [comment]
Hey @rickykissoon that's a good catch. The release of `create-react-app` v5 broke our script. 

It should be working again after a bump of the version with:

#759

**Comment by rickykissoon** [comment]
Awesome, thanks for the quick response!
