### ISSUE TITLE
create-contentful-app command fails to build bootstrap

### ISSUE THREAD

**Issue by dmbdesignpdx** [contentful/create-contentful-app#784]
Hello, I've encountered something odd: I cannot get a new Contentful app bootstrap to build.

### Steps to reproduce

1. `npx @contentful/create-contentful-app init my-first-app`
2. give permission for `npx` to continue

### Expected behavior
`create-contentful-app` to build a bootstrapped directory called 'my-first-app'

### Actual behavior
Build fails with the following warning:
```
You are running `create-react-app` 4.0.3, which is behind the latest release (5.0.0).

We no longer support global installation of Create React App.

Please remove any global installs with one of the following commands:
- npm uninstall -g create-react-app
- yarn global remove create-react-app

The latest instructions for creating a new app can be found here:
https://create-react-app.dev/docs/getting-started/
```

The suggested fix does not work because I do not have `create-react-app` installed globally.

Following the instructions from the provided link, running `npx create-react-app my-app` works just fine.

### Versions
node: 16.13.1
npm: 8.1.2
macOS: 12.1

Please let me know, if there is any other information that is needed. Thank you.

**Comment by shikaan** [comment]
Hello @dmbdesignpdx and thanks for reaching out!

We have managed to reproduce the issue and we're currently working on fixing it. Me or one of my colleagues will update this thread as soon as we are ready with a fix.

Thanks again and apologies for the inconvenience

**Comment by Jwhiles** [comment]
I believe this issue is now fixed. Please let us know if you have any further problems @dmbdesignpdx
