### ISSUE TITLE
coa-2.1.3 dependency

### ISSUE THREAD

**Issue by jasperkuipers** [contentful/create-contentful-app#793]
Hi Contentful-team,

I tried to use this package thru the npx command, but I ended with a non-installed application because of a coa-2.1.3 dependency. Did anyone noticed it as well and is there a fix for this, because this package contains vulnerabilities?

Kind regards,

Jasper

**Comment by kdamball** [comment]
Hi @jasperkuipers, I tried fresh installation using `npx @contentful/create-contentful-app init my-app` and my coa version defaulted to `2.0.2`. Could you verify that you're also getting this?

**Comment by jasperkuipers** [comment]
I tried it with the default registry and it worked. Apparently it had something to do with our package manager.

Thansk!
